title: Leyenda Blanca
description: Toda la actualidad del Real Madrid. Noticias, fichajes y opinión.
url: "https://leyendablanca1902.duckdns.org"

# Aquí cargamos el diseño profesional
remote_theme: "daattali/beautiful-jekyll@6.0.1"

plugins:
  - jekyll-paginate
  - jekyll-sitemap

# Configuración para compartir noticias
share-links-active:
  twitter: true
  facebook: true
  linkedin: false
  whatsapp: true

navbar-links:
  Plantilla: "plantilla"
  Resultados:
 "https://www.google.com/search?q=clasificacion+la+liga"
  Sobre el Blog: "about"


# Esto activa los botones debajo de cada post
show-share-links: true
