title: Leyenda Blanca
description: Toda la actualidad del Real Madrid. Noticias, fichajes y opinión.
url: "https://leyendablanca1902.duckdns.org"

# Aquí cargamos el diseño profesional
remote_theme: "daattali/beautiful-jekyll@6.0.1"

plugins:
  - jekyll-paginate
  - jekyll-sitemap
